apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  replicas: {{.Values.replicaCount}}
  podManagementPolicy: {{ .Values.podManagementPolicy}}
  serviceName: {{ include "clickhouse.fullname" . }}-clickhouse
  selector:
    matchLabels:
      {{- include "clickhouse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clickhouse.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostNetwork: {{ .Values.hostNetwork}}
      dnsPolicy: {{ tpl .Values.dnsPolicy . }}
      imagePullSecrets:
        {{- with .Values.imagePullSecrets }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.chmodContainer.enabled }}
      initContainers:
        - name: clickhouse-init
          image: "{{ tpl .Values.image.repository . }}:{{ tpl (toString .Values.image.tag) . }}"
          volumeMounts:
          - name: clickhouse-path
            mountPath: /var/lib/clickhouse/
          - name: clickhouse-storage-path
            mountPath: /var/lib/clickhouse_storage/
          command: ['sh', '-c', 'chown clickhouse:clickhouse /var/lib/clickhouse_storage;chown clickhouse:clickhouse /var/lib/clickhouse/']
      {{- end }}
      containers:
        - name: clickhouse
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ tpl .Values.image.repository . }}:{{ tpl (toString .Values.image.tag) . }}"
          imagePullPolicy: {{ tpl .Values.image.pullPolicy . }}
          ports:
            - name: tcp
              containerPort: 9000
              protocol: TCP
          env:
            - name: CLICKHOUSE_USER
              value: {{.Values.enviroments.CLICKHOUSE_USER}}
            - name: CLICKHOUSE_PASSWORD
              value: {{.Values.enviroments.CLICKHOUSE_PASSWORD}}
          readinessProbe:
            tcpSocket:
              port: tcp
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: tcp
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: clickhouse-path
            mountPath: /var/lib/clickhouse/
          - name: clickhouse-storage-path
            mountPath: /var/lib/clickhouse_storage/
        {{- range .Values.storageConfig.extraClickhousePath }}
          - name: {{ .volumeName }}
            mountPath: {{ .mountPath }}
        {{- end }}
      volumes:
      {{- if eq ( tpl .Values.storageConfig.generateType . ) "hostPath" }}
        - name: clickhouse-path
          hostPath:
            path: {{ tpl .Values.storageConfig.hostPath . }}/clickhouse
            type: DirectoryOrCreate
        - name: clickhouse-storage-path
          hostPath:
            path: {{ tpl .Values.storageConfig.hostPath . }}/clickhouse-storage
            type: DirectoryOrCreate
      {{- end }}
